Controllers/AuctionController.cs
using System;
using AuctionSite.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuctionSite.Controllers
{
    //this is the members area
    //if not logged in, should be sent back to home!

    [RequireHttps]
    [Authorize(Policy = "paid")]
    public class AuctionController : Controller
    {
        private repo repo;

        public AuctionController(repo repo) => this.repo = repo;

        public IActionResult Index(Guid id) => View(repo.GetAuctionInformation(id));

        public IActionResult IndexPartial(Guid id) => PartialView("_AuctionPartial", repo.GetAuctionInformation(id));
    }
}

Controllers/AuctionsController.cs
using System;
using AuctionSite.DAL;
using AuctionSite.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuctionSite.DAL.Identity;
using AuctionSite.Helpers;
using Microsoft.AspNetCore.Identity;
using SuiteShared.DAL.Models;

namespace AuctionSite.Controllers
{
    //[Authorize(Policy = "paid")]
    [RequireHttps]
    public class AuctionsController : Controller
    {
        private readonly repo repo;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<AuctionUser> userManager;
        private readonly SubscriptionHelper SubHelper;
        private readonly SignInManager<AuctionUser> SignInManager;
        AuctionContext dbcontext = new AuctionContext();

        //List<Auction> filteredAuctionsWithoutStateRestriction = new List<Auction>();
        public AuctionsController(repo repo,
            RoleManager<IdentityRole> RoleManager,
            UserManager<AuctionUser> UserManager,
            SubscriptionHelper SubHelper,
            SignInManager<AuctionUser> SignInManager)
        {
            this.repo = repo;
            this.roleManager = RoleManager;
            this.userManager = UserManager;
            this.SubHelper = SubHelper;
            this.SignInManager = SignInManager;
        }

        public async Task<IActionResult> Index(uint cbmin = 0, uint cbmax = 0,
            uint mbmin = 0, uint mbmax = 0,
            string states = "", string propertyType = "", string sellerType = "",
            string sortby = "bm", string displaykey = "Comfortable", bool favonly = false)
        {
            #region PDT bug workaround
            var user = await this.userManager.GetUserAsync(User);
            //if (!user.SubscriptionConfirmed &&
            //        user.SubscribedAt.AddHours(6) < DateTime.UtcNow)
            //{
            //    await SubHelper.CancelUserSubscription(user.Email);
            //    await SignInManager.RefreshSignInAsync(user);
            //    return RedirectToAction("manage", "Account");
            //}
            #endregion


            var statesList = string.IsNullOrEmpty(states) ? new List<string>() : states.Split(',').ToList();
            var propertyList = string.IsNullOrEmpty(propertyType) ? new List<string>() : propertyType.Split(',').ToList();
            var sellerList = string.IsNullOrEmpty(sellerType) ? new List<string>() : sellerType.Split(',').ToList();
            var filter = repo.GenerateFullPredicate(user.Id, cbmin, cbmax, mbmin, mbmax, statesList, propertyList, sellerList, favonly);
            var filterExceptState = repo.GeneratePredicateWithoutState(user.Id, cbmin, cbmax, mbmin, mbmax, statesList, propertyList, sellerList, favonly);
            var filterExceptPropertyType = repo.GeneratePredicateWithoutPropertyType(user.Id, cbmin, cbmax, mbmin, mbmax, statesList, propertyList, sellerList, favonly);
            var filterExceptSellerType = repo.GeneratePredicateWithoutSellerType(user.Id, cbmin, cbmax, mbmin, mbmax, statesList, propertyList, sellerList, favonly);
            var filteredAuctions = repo.GetAllAuctions(out var count, filter, sortby);
            var filteredAuctionsWithoutStateRestriction = repo.GetAllAuctions(out _, filterExceptState, sortby);
            var filteredAuctionsWithoutTypeRestriction = repo.GetAllAuctions(out _, filterExceptPropertyType, sortby);
            var filteredAuctionsWithoutSellerRestriction = repo.GetAllAuctions(out _, filterExceptSellerType, sortby);
            ViewBag.host = Request.Host.Value;
            ViewBag.minCurrentbid = repo.GetAuctionsCurrentBidMin();
            ViewBag.maxCurrentbid = repo.GetAuctionsCurrentBidMax();
            ViewBag.cbmin = cbmin == 0 ? ViewBag.minCurrentbid : cbmin;
            ViewBag.cbmax = cbmax == 0 ? ViewBag.maxCurrentbid : cbmax;
            ViewBag.minMbid = repo.GetAuctionsMBidMin();
            ViewBag.maxMbid = repo.GetAuctionsMBidMax();
            ViewBag.mbmin = mbmin == 0 ? ViewBag.minMbid : mbmin;
            ViewBag.mbmax = mbmax == 0 ? ViewBag.maxMbid : mbmax;
            var auctionStates = repo.GetAuctionsStates(statesList, filteredAuctionsWithoutStateRestriction);
            ViewBag.states = auctionStates.OrderBy(s => s.StateName);
            ViewBag.propertyType = repo.GetPropertyList(propertyList, filteredAuctionsWithoutTypeRestriction);
            ViewBag.sellerType = repo.GetSellerList(sellerList, filteredAuctionsWithoutSellerRestriction);
            //ViewBag.resultsFound = count;
            ViewBag.resultsFound = filteredAuctions.Where(a => a.AuctionCloses >= DateTime.Now).Count(); // by me
            ViewBag.sort = sortby;
            ViewBag.denisty = displaykey;
            ViewBag.favAuctions = repo.GetFavAuctions(user.Id);
            ViewBag.favonly = favonly;
            var auctions = filteredAuctions.Where(a => a.AuctionCloses >= DateTime.Now).Skip(0).Take(20).ToList();
            //List<Auction> auctions = new List<Auction>(auctList.Where(a => a.AuctionCloses >= DateTime.Now));
            auctions.ForEach(a => a.Link = "https://www.bid4assets.com" + a.Link);
            
            return View(auctions);
        }

        public async Task<IActionResult> IndexAjax(ushort skip, uint cbmin = 0, uint cbmax = 0,
            uint mbmin = 0, uint mbmax = 0, string states = "", string propertyType = "", string sellerType = "",
            string sortby = "bm", string displaykey = "Comfortable", bool favonly = false)
        {
            var statesList = string.IsNullOrEmpty(states) ? new List<string>() : states.Split(',').ToList();
            var propertyList = string.IsNullOrEmpty(propertyType) ? new List<string>() : propertyType.Split(',').ToList();
            var sellerList = string.IsNullOrEmpty(sellerType) ? new List<string>() : sellerType.Split(',').ToList();
            ViewBag.host = Request.Host.Value;
            var user = await this.userManager.GetUserAsync(User);
            ViewBag.favAuctions = repo.GetFavAuctions(user.Id);
            ViewBag.favonly = favonly;
            var filter = repo.GenerateFullPredicate(user.Id, cbmin, cbmax, mbmin, mbmax, statesList, propertyList, sellerList, favonly);
            var results = repo.GetAuctions(out var count, filter, sortby, skip);

            results.ForEach(a => a.Link = "https://www.bid4assets.com" + a.Link);

            if (displaykey == "Comfortable")
                return results.Any()
                    ? PartialView("_AuctionsPartial", results.Where(a => a.AuctionCloses >= DateTime.Now).Distinct().ToList())
                    : (IActionResult)BadRequest("non found");
            return results.Any()
                ? PartialView("_CompactAuctionsPartial", results.Where(a => a.AuctionCloses >= DateTime.Now).Distinct().ToList())
                : (IActionResult)BadRequest("non found");
        }

        public async Task<IActionResult> FavAuctionToggle(Guid AuctionId)
        {
            var user = await this.userManager.GetUserAsync(User);
            if (repo.GetFavAuctions(user.Id).All(a => a != AuctionId))
            {
                repo.AddFavAuction(new UserFavAuction
                {
                    AuctionId = AuctionId,
                    AuctionUserId = user.Id
                });
                return Ok();
            }
            else
            {
                repo.RemoveFavAuction(user.Id, AuctionId);
                return Ok("removed");
            }
        }

        [Produces("application/json")]
        [HttpGet]
        public async Task<IActionResult> SearchState(string state)
        {
            try
            {
                var statesList = new List<string>();

                if (!String.IsNullOrEmpty(state))
                {
                    state = state.ToLower();
                    statesList = (from a in dbcontext.Auctions where a.State.ToLower().StartsWith(state) select a.State).Distinct().ToList();
                }
                else
                {
                    statesList = (from a in dbcontext.Auctions select a.State).Distinct().ToList();
                }
                return Ok(statesList);
            }
            catch (Exception e)
            {
                return BadRequest();
            }
        }   

        public List<AuctionStateViewModel> GetFilterStates(string state)
        {
            var statesList = new List<string>();
            if (!String.IsNullOrEmpty(state))
            {
                state = state.ToLower();
                statesList = (from a in dbcontext.Auctions where a.State.ToLower().StartsWith(state) select a.State).Distinct().ToList();
            }
            else
            {
                statesList = (from a in dbcontext.Auctions select a.State).Distinct().ToList();
            }


            //var locationFilters = repo.GetAuctionsStates(statesList, filteredAuctionsWithoutStateRestriction);

            List<AuctionStateViewModel> locationFilters = new List<AuctionStateViewModel>();
            statesList.ForEach(s =>
            {
                locationFilters.Add(new AuctionStateViewModel()
                {
                    StateName = s,
                    Count = dbcontext.Auctions.Where(a => a.AuctionCloses >= DateTime.Now).Count(a => a.State == s),
                    //Filtered = dbcontext.Auctions.Any(a => a.State == s)
                    Filtered = false
                });
            });

            if (locationFilters != null)
            {
                ViewBag.stateFilter = locationFilters;
               return locationFilters;
            }
            else
            {
                return null;
            }
        }
    }
}

Controllers/ScrapperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SuiteShared.DAL.Models;
using AuctionSite.DAL;
using Microsoft.EntityFrameworkCore;

namespace AuctionSite.Controllers
{
    public class ScrapperController : Controller
    {
        public AuctionContext dbContext = new AuctionContext();

        public IActionResult Index()
        {
            var aucData = (from p in dbContext.Auctions select p).ToList();

            return View(aucData);
        }
    }
}

Views/Shared/_AuctionsPartial.cshtml
@using Microsoft.AspNetCore.Identity.UI.Pages.Internal
@using SuiteShared.DAL.Models

@model List<Auction>

@{int i = 1;}

@foreach (Auction auction in Model)
{

    var imgUrl = (Url.Action("GetAuctionImage", "imgs", new { AuctionId = auction.AuctionId }, "https", (string)ViewBag.host));
    var thumbUrl = (Url.Action("GetAuctionThumb", "imgs", new { AuctionId = auction.AuctionId }, "https", (string)ViewBag.host));
    var quickViewUrl = (Url.Action("IndexPartial", "Auction", new { id = auction.AuctionId }, "https", (string)ViewBag.host));
    <div class="row auction-row" auctionId="@auction.AuctionId">
        <div class="col-md-2 col-lg-2 col-xs-2 col-sm-2" style="height: 100%; vertical-align: middle; display: flex; padding: 0;">
            <div href='@thumbUrl' class="auctionimg" style='background-image: url("@imgUrl"); margin: auto; min-width: 133px; height: 100px; background-size: cover;'>
                <div class="hint" style="display: none;">
                    <i class="fa fa-2x fa-search-plus" aria-hidden="true"></i>
                </div>
            </div>
        </div>
        <div class="auction-info-wrapper col-md-10 col-lg-10 col-xs-10 col-sm-10">
            <h5><a target="_blank" href="@(Url.Action("index", "auction", new { id = auction.AuctionId }, "https", (string) ViewBag.host))">@(auction.AuctionTitle.Length > 62 ? auction.AuctionTitle.Substring(0, 62) + "..." : auction.AuctionTitle)</a></h5>
            <div class="auction-time-left">Close at: @auction.AuctionCloses.ToString("dd MMM HH:mm")</div>
            <div class="location">
                <span class="strong">Location: </span>
                @{
                    if (auction.Address.Contains("\r\n"))
                    {
                        auction.Address = auction.Address.Replace("\r\n", " ");
                    }
                }

                <a href="" id="addr@(i)" data-toggle="modal" onclick="map('@auction.Address');" data-target="#mapModel">@(auction.Address.Length > 70 ? auction.Address.Substring(0, 70) + "..." : auction.Address)</a>
                @*<a href="" id="addr@(i)" data-toggle="modal" onclick="locate('@auction.Address');" data-target="#mapModel">@(auction.Address.Length > 70 ? auction.Address.Substring(0, 70) + "..." : auction.Address)</a>*@

                <!-- Modal -->
                <div class="modal fade" id="mapModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header" style="padding: 5px 5px 5px 5px">
                                <h5 class="modal-title" id="exampleModalLongTitle" style=" margin: 0 0 0 15px">Location</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <style>
                                    #map-div {
                                        height: 380px;
                                        width: 480px;
                                        background-color: #CCC;
                                    }
                                </style>
                                <div id="map-div" style="height: 400px; width: 500px;">
                                    <iframe id="mapframe" name="mapframe" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDBaJ4FbneVPdcGbUOrNgo6y0oI7GkN9Mk&q=" width="500" height="400" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                                </div>
                            </div>
                            <div class="modal-footer" style="padding: 5px 5px 5px 5px">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Model End-->
            </div>

            <div class="bidsInfo">
                <table>
                    <tr>
                        <td>Bids</td>
                        <td><span class="strong">@auction.NumberOfBids</span></td>
                    </tr>
                    <tr>
                        <td>Min. Bid</td>
                        <td><span class="strong">@auction.MinimumBid.ToString("C")</span></td>
                    </tr>
                    <tr>
                        <td>Current Bid</td>
                        <td><span class="strong">@auction.CurrentBid.ToString("C")</span></td>
                    </tr>
                    <tr>
                        <td>Bid Increment</td>
                        <td><span class="strong">@auction.BidIncrement.ToString("C")</span></td>
                    </tr>

                </table>
            </div>
            <div class="geo-info">
                <table>
                    <tr>
                        <td style="width: 45px;"><span class="strong">State</span>: </td>
                        <td style="width: 120px;">@auction.State</td>
                        <td style="width: 40px;"><span class="strong">City</span>: </td>
                        <td style="width: 120px;">@auction.City</td>
                        @if (!string.IsNullOrEmpty(@auction.County))
                        {
                            <td style="width: 60px;"><span class="strong">County</span>: </td>
                            <td>@auction.County</td>
                        }
                    </tr>
                </table>

            </div>
            <div class="property-info">
                <table>
                    <tr>
                        @if (!string.IsNullOrEmpty(auction.LotSize))
                        {
                            <td style="width: 100px;">Lot size:</td>
                            <td style="width: 100px;">@auction.LotSize</td>
                        }
                        @if (auction.NumberOfBathrooms != 0 || auction.NumberOfBedrooms != 0)
                        {
                            <td>Bedrooms:</td>
                            <td align="left">@auction.NumberOfBedrooms</td>
                            <td>Bathrooms:</td>
                            <td align="left">@auction.NumberOfBathrooms</td>
                        }
                    </tr>
                    <tr>
                        <td>Annual Tax:</td>
                        <td style="width:91px;" align="left">@auction.AnnualTaxes.ToString("C")</td>
                        <td>Premium:</td>
                        <td style="width:84px;" align="left">@(auction.BuyersPremium)%</td>
                        @if (!string.IsNullOrEmpty(@auction.HOAFee))
                        {
                            <td>HOA Fee:</td>
                            <td align="left">@auction.HOAFee</td>
                        }
                    </tr>
                    <tr>
                        <td>Selling Price</td>
                        <td><span class="strong">@auction.TotalAssessedValues.ToString("C")</span></td>
                    </tr>
                </table>
            </div>
            <a class="btn btn-success btn-xs btn-view-auction cta-btn" partial-link="@quickViewUrl">Auction Details</a>
            <a target="_blank" class="btn btn-success btn-xs btn-bid-auction cta-btn" href="@auction.Link">Bid on it!</a>
            <a class="btn btn-success cta-btn fav btn-fav-auction" AuctionId="@auction.AuctionId"
               link="@Url.Action("FavAuctionToggle", "Auctions", new { AuctionId = auction.AuctionId })">
                @if (((List<Guid>)ViewBag.favAuctions).Any(a => a == auction.AuctionId))
                {
                    <i class="fa fa-heart" aria-hidden="true"></i>
                }
                else
                {
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                }
            </a>
        </div>
    </div>
    {
        i++;
    }

}

<script>

    function map(id) {
        var url = 'https://www.google.com/maps/embed/v1/place?key=AIzaSyDBaJ4FbneVPdcGbUOrNgo6y0oI7GkN9Mk&q=' + id;
        $("#mapframe").attr('src', url);
    }

</script>

@*<script>
        var geocoder;
        var map;
        var address = "new york city";
        var loc = "new york";

        function locate(addr) {
            loc = addr;
            alert(loc);
            initMap();

        }

        function initMap() {
            var map = new google.maps.Map(document.getElementById('map-div'), {
                zoom: 8,
                center: { lat: -34.397, lng: 150.644 }
            });
            geocoder = new google.maps.Geocoder();
            codeAddress(geocoder, map);
        }

        function codeAddress(geocoder, map) {
            geocoder.geocode({ 'address': loc }, function (results, status) {
                if (status === 'OK') {
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location
                    });
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }


    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDBaJ4FbneVPdcGbUOrNgo6y0oI7GkN9Mk&callback=initMap">
    </script>*@

Views/Shared/_Layout.cshtml
@using AuctionSite.DAL.Identity
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AuctionUser> SignInManager
@inject UserManager<AuctionUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="ScreenOrientation" content="autoRotate:disabled">
    <title>Tsaishen</title>

    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/overhang.min.js"></script>
    <script src="~/js/bootstrap-slider.js"></script>
    <script src="~/js/site.js"></script>
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js" id="mob_script"></script>*@
    @*<script src="https://code.jquery.com/jquery-1.12.4.js"></script>*@
    @*<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/fontawesome/4.7.0/css/font-awesome.min.css" />
    <link href="~/css/overhang.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap-slider.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" id="site" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" id="mobile" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" id="w3-mob">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" />
    @*<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />*@

    <link rel="icon" type="image/x-icon" href="~/imgs/fav_logo.ico" src="" />
</head>
<body>

    <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img width="150px" src="/imgs/logo.png" /></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">


                    <li id="phoneedu" style="display:none"><a class="btn big-login" style="font-family:sans-serif;font-weight:600;" href="#education">Education</a></li>
                    <li id="phoneabtus" style="display:none"><a class="btn big-login" style="font-family:sans-serif;font-weight:600" href="#aboutus">About Us</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        var usr = await UserManager.GetUserAsync(User);

                        if (User != null)
                        {
                            <li class="btn big-login" style="font-family:sans-serif !important;font-weight:600;"><a asp-area="" asp-controller="Auctions" asp-action="Index">Auctions</a></li>
                        }

                    }
                    @*<li><a asp-area="" asp-controller="Scrapper" asp-action="Index">Auctions Data</a></li>*@
                </ul>
                <partial name="_LoginPartial" />
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content" style="width:100%;">
        @RenderBody()
    </div>
    <div id="imgOverlay">
        <img />
    </div>
    <div id="quickViewOverlay">
        <div class="container-fluid body-content"></div>
    </div>
    <style>


        .ftr {
            text-align: center;
            margin: 10px 0px 0px 0px;
            background-color: white;
        }
    </style>

    <div id="id01" class="w3-modal">
        <div class="w3-modal-content">
            <div class="w3-container">
                <h4 class="w3-display-topleft">Register</h4>
                <span onclick="document.getElementById('id01').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                <div class="error"></div>
                <div class="form">
                    <form method="" html="{:multipart=>true}" id="mob-reg" data-remote="true" action="" accept-charset="UTF-8">
                        <input id="reg-email" class="form-control" type="text" placeholder="Email" name="email">
                        <input id="reg-password" class="form-control" type="password" placeholder="Password" name="password">
                        <input id="reg-password_confirmation" class="form-control" type="password" placeholder="Repeat Password" name="password_confirmation">
                        <input class="btn btn-default btn-register cta-btn" type="button" value="Create account" name="commit" onclick="registerAjax('mob')">
                    </form>
                </div>
                <div class="">
                    <span>Already have an account?</span>
                    <a href="#" onclick="document.getElementById('id02').style.display = 'block';document.getElementById('id01').style.display='none'">Login</a>
                </div>
            </div>
        </div>
    </div>
    <div id="id02" class="w3-modal">
        <div class="w3-modal-content">
            <div class="w3-container">
                <h4 class="w3-display-topleft">Login</h4>
                <span onclick="document.getElementById('id02').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                <div class="error"></div>
                <div class="form ">
                    <form method="" action="" id="mob-login" accept-charset="UTF-8">
                        <input id="login-email-mob" class="form-control" type="text" placeholder="Email" name="email">
                        <input id="login-password-mob" class="form-control" type="password" placeholder="Password" name="password">
                        <input class="btn btn-default btn-login cta-btn" type="button" value="Login" onclick="loginAjax()">
                    </form>
                </div>
                <div class="">
                    <span>
                        Looking to <a href="#" onclick="document.getElementById('id01').style.display = 'block';document.getElementById('id02').style.display='none'">create an account?</a>
                        <br />
                        <a href="#" onclick="document.getElementById('id04').style.display = 'block';document.getElementById('id02').style.display='none'">Forgot password?</a>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div id="id03" class="w3-modal">
        <div class="w3-modal-content">
            <div class="w3-container">
                <h4 class="w3-display-topleft">Confirm code</h4>
                <span onclick="document.getElementById('id03').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                <div class="form">
                    <form method="" action="" id="mob-confirm" accept-charset="UTF-8">
                        <input id="confirm-email" class="form-control" type="text" placeholder="Email" name="email">
                        <textarea id="confirm-code" class="form-control" style="margin-bottom: 10px; color: black;" placeholder="confirmation code" name="confirmation code" width="80%" rows="8"></textarea>
                        <input class="btn btn-default btn-confirm cta-btn" type="button" value="confirm" onclick="confirmAjax()">
                    </form>
                </div>
                <div class="">
                    <span>Didn't receive code?</span>
                    <a href="javascript: resendCode();">Resend code</a>
                </div>
            </div>
        </div>
    </div>
    <div id="id04" class="w3-modal">
        <div class="w3-modal-content">
            <div class="w3-container">
                <h4 class="w3-display-topleft">Send forget Password email</h4>
                <span onclick="document.getElementById('id04').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                <div class="form">
                    <form method="" action="" id="mob-forget" accept-charset="UTF-8">
                        <input id="forget-email" class="form-control" type="text" placeholder="Email" name="email">
                        <input class="btn btn-default btn-forget cta-btn" type="button" value="Send email" onclick="forgotAjax()">
                    </form>
                </div>
                <div class="">
                    <span>Didn't receive code?</span>
                    <a href="javascript: resendCode();">Resend code</a>
                </div>
            </div>
        </div>
    </div>
    <footer class="ftr">
        <div class="container">
            <div class="row">
                <p class="center">The entirety of this site is protected by copyright © 2019-2020 Tsaishen.co.</p>
            </div>
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-2 center"><a href="~/Home/Terms"><u>Terms</u></a></div>
                <div class="col-sm-2 center"><a href="~/Home/PrivacyPolicy"><u>Privacy Policy</u></a></div>
                <div class="col-sm-2 center"><a href="~/Home/IncomeDisclosure"><u>Income Disclosures</u></a></div>
                <div class="col-sm-2 center"><a href="~/Home/Contact"><u>Contact Us</u></a></div>
                <div class="col-sm-2 center"><a href="#"><u>Affiliates</u></a></div>
                <div class="col-sm-1"></div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $('.navbar-nav>li>a').on('click', function () {
            $('.navbar-collapse').collapse('hide');
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>